## A series of tests for the fetch math library (and associated python bindings)

### initial setup

In [1]:
# import fetch
import numpy as np
import fetch.math as fm
from fetch.math import NDArrayDouble
#from fetch.math import statistics as stats

In [2]:
def simple_test_fn(a, b):
    if (a == b):
        print("test passed!")
    else:
        print("FAILURE")
    return

In [3]:
def test_fn(np_arr, fetch_arr):
    
    if np.array_equal(np_arr, fetch_arr.ToNumpy()):
        print("test passed!")
    else:
        print("FAILURE")

    return

array([[9., 1., 1., 1., 8., 1., 1., 7.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

SyntaxError: invalid syntax (<ipython-input-5-af8388515beb>, line 1)

### Check To and From Numpy

In [6]:
shape = [1,2,3,4,5]
n_dims = len(shape)

In [7]:
# To Numpy Test
np_z = np.zeros(shape)
fetch_z = NDArrayDouble.Zeros(shape)
test_fn(np_z, fetch_z)

test passed!


In [8]:
# From Numpy Test
np_z = np.zeros(shape)
fetch_z.FromNumpy(np_z)
test_fn(np_z, fetch_z)

test passed!


### Check zeroes, ones, copy, and equality

In [9]:
shape = [1,2,3,4,5]
n_dims = len(shape)

In [10]:
np_x = np.zeros(shape)
fetch_x = NDArrayDouble.Zeros(shape)
np_y = np.ones(shape)
fetch_y = NDArrayDouble.Ones(shape)

fetch_z = NDArrayDouble(shape)

In [11]:
fetch_z = fetch_x
simple_test_fn(fetch_z, fetch_x)

test passed!


In [12]:
test_fn(np_x, fetch_z)

test passed!


In [13]:
fetch_z = fetch_y
simple_test_fn(fetch_z, fetch_y)

test passed!


In [14]:
if not (fetch_z != fetch_y):
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


### Check basic element-wise arithmetic operators

In [15]:
shape = [3, 4]
n_dims = len(shape)
np_x = np.random.random(shape)
fetch_x.FromNumpy(np_x)
np_y = np.random.random(shape)
fetch_y.FromNumpy(np_y)

In [16]:
np_test = np_x + np_y
fetch_z = fetch_x + fetch_y
test_fn(np_test, fetch_z)

test passed!


In [17]:
np_test += np_x
fetch_z += fetch_x
test_fn(np_test, fetch_z)

test passed!


In [18]:
np_test = np_x - np_y
fetch_z = fetch_x - fetch_y
test_fn(np_test, fetch_z)

test passed!


In [19]:
np_test -= np_x
fetch_z -= fetch_x
test_fn(np_test, fetch_z)

test passed!


In [20]:
np_test = np_x * np_y
fetch_z = fetch_x * fetch_y
test_fn(np_test, fetch_z)

test passed!


In [21]:
np_test *= np_x
fetch_z *= fetch_x
test_fn(np_test, fetch_z)

test passed!


In [22]:
np_test = np_x / np_y
fetch_z = fetch_x / fetch_y
test_fn(np_test, fetch_z)

test passed!


In [23]:
np_test /= np_x
fetch_z /= fetch_x
test_fn(np_test, fetch_z)

test passed!


### check basic array * scalar arithmetic operations

In [24]:
shape = [3, 4]
n_dims = len(shape)
fetch_z = NDArrayDouble.Zeros(shape)

shape = [3, 4]
n_dims = len(shape)
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)

In [25]:
np_test = np_x + 7
fetch_z = fetch_x + 7
test_fn(np_test, fetch_z)

test passed!


In [26]:
np_test += 7
fetch_z += 7
test_fn(np_test, fetch_z)

test passed!


In [27]:
np_test = np_x - 7
fetch_z = fetch_x - 7
test_fn(np_test, fetch_z)

test passed!


In [28]:
np_test -= 7
fetch_z -= 7
test_fn(np_test, fetch_z)

test passed!


In [29]:
np_test = np_x * 7
fetch_z = fetch_x * 7
test_fn(np_test, fetch_z)

test passed!


In [30]:
np_test *= 7
fetch_z *= 7
test_fn(np_test, fetch_z)

test passed!


In [31]:
np_test = np_x / 7
fetch_z = fetch_x / 7
test_fn(np_test, fetch_z)

test passed!


In [32]:
np_test /= 7
fetch_z /= 7
test_fn(np_test, fetch_z)

test passed!


### check broadcasting arithmetic

In [33]:
shape = [2, 1, 2]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)

shape2 = [1, 3, 2]
np_y = np.random.random(shape2)
fetch_y = NDArrayDouble(shape2)
fetch_y.FromNumpy(np_y)

broadcast_shape = [max(a,b) for a,b in zip(shape, shape2)]

In [34]:
np_out = np_x + np_y
fetch_out = fetch_x + fetch_y
test_fn(np_out, fetch_out)

print(np_out)
fetch_out.ToNumpy()

FAILURE
[[[0.75356799 1.02900481]
  [1.04350973 0.15680268]
  [0.86071685 0.19653024]]

 [[0.65709897 1.41837298]
  [0.94704071 0.54617085]
  [0.76424783 0.5858984 ]]]


array([[[0.75356799, 0.55162647],
        [1.23094633, 1.02900481],
        [1.04350973, 0.84156822]],

       [[0.26227518, 0.54617085],
        [0.76424783, 1.0481435 ],
        [0.30200274, 0.5858984 ]]])

In [35]:
np_out = np_x - np_y
fetch_out = fetch_x - fetch_y
test_fn(np_out, fetch_out)

FAILURE


In [36]:
np_out = np_x * np_y
fetch_out = fetch_x * fetch_y
test_fn(np_out, fetch_out)

FAILURE


In [37]:
np_out = np_x / np_y
fetch_out = fetch_x / fetch_y
test_fn(np_out, fetch_out)

FAILURE


In [38]:
# The following shows examples of inline arithmetic with broadcasting - in numpy they do not support this
shape = [3, 1, 5]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

shape2 = [1, 7, 5]
np_y = np.ones(shape2)
fetch_y = NDArrayDouble.Ones(shape2)

broadcast_shape = [max(a,b) for a,b in zip(shape, shape2)]

In [39]:
try:
    fetch_x += fetch_y
except ValueError:
    print("test passed!")

broadcast shape ( [3, 7, 5] ) does not match shape of output array ( [3, 1, 5] )
test passed!


In [40]:
try:
    fetch_x -= fetch_y
except ValueError:
    print("test passed!")

broadcast shape ( [3, 7, 5] ) does not match shape of output array ( [3, 1, 5] )
test passed!


In [41]:
try:
    fetch_x *= fetch_y
except ValueError:
    print("test passed!")

broadcast shape ( [3, 7, 5] ) does not match shape of output array ( [3, 1, 5] )
test passed!


In [42]:
try:
    fetch_x /= fetch_y
except ValueError:
    print("test passed!")

broadcast shape ( [3, 7, 5] ) does not match shape of output array ( [3, 1, 5] )
test passed!


### check array slicing and slice assignment

In [43]:
shape = [2, 3]
np_x = np.random.random(shape)
fetch_x.FromNumpy(np_x)
print(np_x)
print("\n\n")
print(fetch_x.ToNumpy())

[[0.13735753 0.74811555 0.88920103]
 [0.87221452 0.75811776 0.57798115]]



[[0.13735753 0.74811555 0.88920103]
 [0.87221452 0.75811776 0.57798115]]


In [44]:
np_y = np_x[0:1, 1:2]
fetch_y = fetch_x[0:1, 0:1]

print(np_y)
print("\n\n")
# print(fetch_y.ToNumpy())
print(fetch_x[1, 1])

[[0.74811555]]



0.872214516603849


In [45]:
shape = [3, 4, 5, 8, 2]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)

In [46]:
np_y = np_x[0:1, 0:2, 2:3, 3:6, 0:1]
fetch_y = fetch_x[0:1, 0:2, 2:3, 3:6, 0:1]
test_fn(np_y, fetch_y)

print(np_y)
fetch_y.ToNumpy()

FAILURE
[[[[[0.64135882]
    [0.76672289]
    [0.54990808]]]


  [[[0.10302763]
    [0.03122374]
    [0.02862529]]]]]


array([[[[[0.54295596],
          [0.39319852],
          [0.45330993]]],


        [[[0.45662238],
          [0.55588491],
          [0.99448922]]]]])

In [47]:
shape = [3, 4, 5, 8, 2]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)
shape = [1, 2, 3, 4, 1]
np_y = np.ones(shape)
fetch_y = NDArrayDouble.Ones(shape)

np_y[0:1, 0:2, 0:3, 0:4, 0:1] = np_x[0:1, 2:4, 2:5, 2:6, 0:1]
fetch_y[0:1, 0:2, 0:3, 0:4, 0:1] = fetch_x[0:1, 2:4, 2:5, 2:6, 0:1]
test_fn(np_y, fetch_y)

test passed!


In [48]:
shape = [3, 4, 5, 8, 2]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

In [49]:
np_y = np_x[1, 2, 3, 6, 1]
fetch_y = fetch_x[1, 2, 3, 6, 1]
simple_test_fn(np_y, fetch_y)

test passed!


In [50]:
shape = [3, 4, 5, 8, 2]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)
shape = [1, 2, 3, 4, 1]
np_y = np.ones(shape)
fetch_y = NDArrayDouble.Ones(shape)

np_y[0, 1, 2, 3, 0] = np_x[2, 3, 4, 5, 1]
fetch_y[0, 1, 2, 3, 0] = fetch_x[2, 3, 4, 5, 1]
test_fn(np_y, fetch_y)

test passed!


### Reshaping tests

In [51]:
shape = [3, 4, 5, 8, 2]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

new_shape = [4, 2, 8, 5, 3]


In [52]:
np_x = np.reshape(np_x, new_shape)
fetch_x.reshape(new_shape)
test_fn(np_x, fetch_x)

test passed!


In [53]:
absurd_shape = [99999, 12]
try:
    fetch_x.reshape(absurd_shape)
except ValueError:
    print("test passed!")

cannot reshape array of size ( 960 ) into shape of( [4, 2, 8, 5, 3] )
test passed!


In [54]:
shape = [3, 4, 5, 8, 2]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

np_x = np_x.flatten()
fetch_x.flatten()
test_fn(np_x, fetch_x)

test passed!


### check dimension reduction max and min functions with axis specification

In [55]:
# max_shape = [7, 4, 6]
# fetch_x = NDArrayDouble(max_shape)
# np_x = np.zeros(max_shape)
# counter = 0
# for i in range(max_shape[0]):
#     for j in range(max_shape[1]):
#         for k in range(max_shape[2]):
#             fetch_x[i, j, k] = counter
#             np_x[i, j, k] = counter
#             counter += 1

In [56]:
# # test taking max and min across all axes one by one
# out_shapes = [[4, 6], [7, 6], [7, 4]]
# for cur_ax in range(0, 3):

#     out_shape = out_shapes[cur_ax]
#     np_max = np_x.max(axis=cur_ax)
#     fetch_max = fetch_x.max(cur_ax)
#     np_min = np_x.min(axis=cur_ax)
#     fetch_min = fetch_x.min(cur_ax)

#     test_fn(np_max, fetch_max)
#     test_fn(np_min, fetch_min)

### check some more functions

In [57]:
shape = [3, 4]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

In [58]:
np_x = np.abs(np_x)
fetch_x.abs(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [59]:
np_x = np.exp(np_x)
fetch_x.exp(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [60]:
np_x = np.exp2(np_x)
fetch_x.exp2(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [61]:
np_x = np.expm1(np_x)
fetch_x.expm1(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [62]:
np_x = np.log(np_x)
fetch_x.log(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [63]:
np_x = np.log10(np_x)
fetch_x.log10(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [64]:
np_x = np.log2(np_x)
fetch_x.log2(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [65]:
np_x = np.log1p(np_x)
fetch_x.log1p(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [66]:
shape = [3, 4]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)


In [67]:
np_x = np.sqrt(np_x)
fetch_x.sqrt(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [68]:
np_x = np.cbrt(np_x)
fetch_x.cbrt(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [69]:
np_x = np.sin(np_x)
fetch_x.sin(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [70]:
np_x = np.cos(np_x)
fetch_x.cos(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [71]:
np_x = np.tan(np_x)
fetch_x.tan(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [72]:
np_x = np.arcsin(np_x)
fetch_x.asin(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [73]:
np_x = np.arccos(np_x)
fetch_x.acos(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [74]:
np_x = np.arctan(np_x)
fetch_x.atan(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [75]:
np_x = np.sinh(np_x)
fetch_x.sinh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [76]:
np_x = np.cosh(np_x)
fetch_x.cosh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [77]:
np_x = np.tanh(np_x)
fetch_x.tanh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [78]:
shape = [3, 4]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

np_x = np.arcsinh(np_x)
fetch_x.asinh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [79]:
shape = [3, 4]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

np_x = np.arccosh(np_x)
fetch_x.acosh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [80]:
np_x = np.arctanh(np_x)
fetch_x.atanh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [81]:
np_x = np.ceil(np_x)
fetch_x.ceil(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [82]:
np_x = np.floor(np_x)
fetch_x.floor(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [83]:
np_x = np.trunc(np_x)
fetch_x.trunc(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [84]:
np_x = np.round(np_x)
fetch_x.round(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [85]:
np_x = np.rint(np_x)
fetch_x.rint(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [86]:
np_x = np.isfinite(np_x)
fetch_x.isfinite(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [87]:
np_x = np.isinf(np_x)
fetch_x.isinf(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [88]:
np_x = np.isnan(np_x)
fetch_x.isnan(fetch_x)
test_fn(np_x, fetch_x)

test passed!


### Now let's get a bit more fancy

In [89]:
shape = [3, 4]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

In [90]:
np.maximum(np_x, 0)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [91]:
def Relu(x):
    if x >= 0:
        return x
    else:
        return 0
    
test_list = [Relu(a) for a in x.ToNumpy()]
z.Relu(x * 1)
test_fn(test_list, z)

NameError: name 'x' is not defined

In [ ]:
z.ToNumpy()

In [ ]:
z.Relu(x * -1)
test_pass_fn(test_list, z)

In [92]:
test_list = np.sign(x.ToNumpy())
z.Sign(x)
test_pass_fn(test_list, z)

NameError: name 'x' is not defined

In [93]:
test_list

NameError: name 'test_list' is not defined

In [94]:
z.Sign(1).ToNumpy()

NameError: name 'z' is not defined

In [95]:
z.Softmax()

NameError: name 'z' is not defined

### Scatter and Gather tests

In [134]:
import tensorflow as tf

In [135]:
g = tf.Graph()
with g.as_default():
    a = tf.Variable(initial_value=[[0, 0, 0, 0],[0, 0, 0, 0]])
    b = tf.scatter_update(a, [0, 1], [[1, 0, 0, 0], [1, 0, 0, 0]])
    c = tf.gather(a, [0, 1], [[1, 0], [1, 0]])
    
np_x = np.zeros([2, 4])
np_y = np.zeros([1, 3])
with tf.Session(graph=g) as sess:
    sess.run(tf.initialize_all_variables())
    np_x = sess.run(b)
    np_y = sess.run(c)

In [136]:
np_x = np.zeros([2, 4])
with tf.Session(graph=g) as sess:
    sess.run(tf.initialize_all_variables())
    np_x = sess.run(b)
    np_y = sess.run(c)

In [139]:
fetch_x = NDArrayDouble.Zeros([2,4])
fetch_x.scatter([1, 1], [0, 1])

test_fn(np_x, fetch_x)
print(np_x)
print(fetch_x.ToNumpy())

FAILURE
[[1 0 0 0]
 [1 0 0 0]]
[[1. 1. 0. 0.]
 [0. 0. 0. 0.]]


In [140]:
fetch_y = NDArrayDouble.Zeros([2,4])
fetch_y = fetch_x.gather([0, 1])

test_fn(np_y, fetch_y)
print(np_y)
print(fetch_y.ToNumpy())

FAILURE
[[1 0 0 0]
 [1 0 0 0]]
[[1. 1. 0. 0.]
 [0. 0. 0. 0.]]


(3, 4)