### Initially, we set up some arrays

In [1]:
import fetch
import numpy as np

In [2]:
from fetch.math import NDArrayDouble
from fetch.math import statistics as stats

In [3]:
shape = [1,2,3,4,5]
n_dims = len(shape)

In [4]:
x = NDArrayDouble(shape)
y = NDArrayDouble(shape)
z = NDArrayDouble(shape)


In [5]:
for i in range(x.size()):
    x[i] = i + 1
    y[i] = -i -1
    z[i] = 5

In [6]:
x.ToNumpy()[:10]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
y.ToNumpy()[:10]

array([ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9., -10.])

### Check copy and equality

In [8]:
y = x
test_pass = 1
for idx in range(len(y.ToNumpy())):
    if (y[idx] - x[idx] != 0):
        test_pass = 0
if test_pass:
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


In [9]:
y.ToNumpy()[:10]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
x.ToNumpy()[:10]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
if(y == x):
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


In [12]:
if not (y != x):
    print("test passed!")
else:
    print("FAILURE!!!!")


test passed!


### Check basic element-wise arithmetic operators

In [13]:
test_list = [a + b for a,b in zip(x.ToNumpy(), y.ToNumpy())]
z = x + y
test_pass = 1
for idx in range(len(test_list)):
    if (z[idx] != test_list[idx]):
        test_pass = 0
if test_pass:
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


In [14]:
test_list = [a - b for a,b in zip(x.ToNumpy(), y.ToNumpy())]
z = x - y
test_pass = 1
for idx in range(len(test_list)):
    if (z[idx] != test_list[idx]):
        test_pass = 0
if test_pass:
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


In [15]:
test_list = [a * b for a,b in zip(x.ToNumpy(), y.ToNumpy())]
z = x * y
test_pass = 1
for idx in range(len(test_list)):
    if (z[idx] != test_list[idx]):
        test_pass = 0
if test_pass:
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


In [16]:
test_list = [a / b for a,b in zip(x.ToNumpy(), y.ToNumpy())]
z = x / y
test_pass = 1
for idx in range(len(test_list)):
    if (z[idx] != test_list[idx]):
        test_pass = 0
if test_pass:
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


### check basic array * scalar arithmetic operations

In [17]:
test_list = [a + 7 for a in x.ToNumpy()]
z = x + 7
test_pass = 1
for idx in range(len(test_list)):
    if (z[idx] != test_list[idx]):
        test_pass = 0
if test_pass:
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


In [18]:
test_list = [a - 7 for a in x.ToNumpy()]
z = x - 7
test_pass = 1
for idx in range(len(test_list)):
    if (z[idx] != test_list[idx]):
        test_pass = 0
if test_pass:
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


In [19]:
test_list = [a * 7 for a in x.ToNumpy()]
z = x * 7
test_pass = 1
for idx in range(len(test_list)):
    if (z[idx] != test_list[idx]):
        test_pass = 0
if test_pass:
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


In [20]:
test_list = [a / 7 for a in x.ToNumpy()]
z = x / 7
test_pass = 1
for idx in range(len(test_list)):
    if (z[idx] != test_list[idx]):
        test_pass = 0
if test_pass:
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


### check array slicing and slice assignment

In [21]:
y = x[0:1, 0:1, 0:2, 0:3, 0:2]

In [22]:
y.Shape()

[1, 1, 2, 3, 2]

In [23]:
y[0:1, 0:1, 0:2, 0:3, 0:2] = x[0:1, 0:1, 0:2, 0:3, 0:2]

In [24]:
some_value = x[0, 0, 1, 2, 1]

In [25]:
y[0,0,1,2,1] = x[0,0,1,2,1]

### check some other basic array methods

In [26]:
y.Flatten().Shape()

[12]

In [27]:
x[:, :, :, :, :].ToNumpy()

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120.])

In [28]:
x[0:1, 0:1, 0:1, 0:1, 0:1].ToNumpy()

array([1.])

In [29]:
stats.Max(x)

120.0

In [30]:
x.Max(1)

2.0

In [31]:
import numpy as np


In [39]:
# na = np.zeros([[0,1,2],[3,4,5],[6,7,8]])
na = np.zeros([3, 3, 3])

new_shape = [3, 3, 3]
e = NDArrayDouble(new_shape)
for i in range(3):
    for j in range(3):
        for k in range(3):
            e[i, j, k] = i + j + k
            na[i, j, k] = i + j + k
#     e[i] = i

In [41]:
na

array([[[0., 1., 2.],
        [1., 2., 3.],
        [2., 3., 4.]],

       [[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]],

       [[2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]]])

In [42]:
e.ToNumpy()

array([0., 1., 2., 1., 2., 3., 2., 3., 4., 1., 2., 3., 2., 3., 4., 3., 4.,
       5., 2., 3., 4., 3., 4., 5., 4., 5., 6.])

In [43]:
na.min(axis=0)

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [47]:
e.Min(0).ToNumpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
e.Min(0).Shape()

[3, 3]