In [1]:
import numpy as np
import fetch.math as fm
from fetch.math import NDArrayDouble
import tensorflow as tf

In [2]:
TOLERANCE = 1e-12
def simple_test_fn(a, b):
    if (abs(a - b) < TOLERANCE):
        print("test passed!")
    else:
        print("FAILURE")
    return

In [3]:
def test_fn(np_arr, fetch_arr):
    
    if np.allclose(np_arr, fetch_arr.ToNumpy()):
        print("test passed!")
    else:
        print("FAILURE")

    return

### Setup

In [4]:
g = tf.Graph()

In [5]:
def reset_arrays(offset=0, shape=[2, 3, 2]):
    # initialise some random arrays
#     shape = [1,2,3,4,5,6]
#     shape = [2,4]
#     shape = [2,3,2]

    # set up the tensorflow / numpy array
    with g.as_default():
        tf_x = tf.to_double(tf.random_uniform(shape, 0.1, 1, dtype=tf.float64)) + offset
        tf_y = tf.to_double(tf.random_uniform(shape, 0.1, 1, dtype=tf.float64)) + offset
    with tf.Session(graph=g) as sess:
        sess.run(tf.global_variables_initializer())
        np_x = sess.run(tf_x)
        np_y = sess.run(tf_y)

    # set up the fetch array
    fetch_x = NDArrayDouble(shape)
    fetch_x.FromNumpy(np_x)
    fetch_y = NDArrayDouble(shape)
    fetch_y.FromNumpy(np_y)

    # set up a test fetch array
    fetch_z = NDArrayDouble(shape)
    
    return np_x, np_y, fetch_x, fetch_y, fetch_z

### tf.log

In [6]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.log(np_x))
fetch_x.log()
test_fn(np_z, fetch_x)

test passed!


### tf.exp

In [7]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.exp(np_x))
fetch_x.exp()
test_fn(np_z, fetch_x)

test passed!


### tf.sqrt

In [8]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.sqrt(np_x))
fetch_x.sqrt()
test_fn(np_z, fetch_x)

test passed!


### tf.div

In [9]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.div(np_x, np_y))
fetch_z = fetch_x / fetch_y
test_fn(np_z, fetch_z)

test passed!


### tf.multiply

In [10]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.multiply(np_x, np_y))
fetch_z = fetch_x * fetch_y
test_fn(np_z, fetch_z)

test passed!


### tf.nn.l2loss

In [11]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.nn.l2_loss(np_x))
fetch_z = fetch_x.l2loss()  
simple_test_fn(np_z, fetch_z)

test passed!


### tf.abs

In [12]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.abs(np_x))
fetch_x.abs()
test_fn(np_z, fetch_x)

test passed!


### tf.nn.relu

In [13]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.nn.relu(np_x))
fetch_x.relu()
test_fn(np_z, fetch_x)

test passed!


### tf.sign

In [14]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.sign(np_x))
fetch_x.sign()
test_fn(np_z, fetch_x)

test passed!


### tf.maximum

In [15]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.maximum(np_x, np_y))

fetch_z.maximum(fetch_x, fetch_y)

test_fn(np_z, fetch_z)

test passed!


### tf.reduce_mean

In [16]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.reduce_mean(np_x, 1))
fetch_z.reduce_mean(fetch_x, 1)
test_fn(np_z, fetch_z)

test passed!


### tf.reduce_sum

In [17]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.reduce_sum(np_x, 1))
fetch_z.reduce_sum(fetch_x, 1)
test_fn(np_z, fetch_z)

test passed!


### tf.boolean_mask

In [20]:
# 1d test
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[10]) # ensure some values are negative
mask = np.random.randint(0, 2, (10))
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.boolean_mask(np_x, mask))
fetch_mask = NDArrayDouble([10])
fetch_mask.FromNumpy(mask)
fetch_z = fetch_x.boolean_mask(fetch_mask)

test_fn(np_z, fetch_z)

test passed!


In [26]:
# 2d test
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[2, 10]) # ensure some values are negative
mask = np.random.randint(0, 2, (2, 10))
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.boolean_mask(np_x, mask))
fetch_mask = NDArrayDouble([10, 2])
fetch_mask.FromNumpy(mask)
fetch_z = fetch_x.boolean_mask(fetch_mask)

print(np_x)
print(mask)
print(np_z)
print(fetch_z.ToNumpy())

test_fn(np_z, fetch_z)

[[-0.25223221  0.38580726  0.28872968  0.10341491  0.29326008  0.21027669
  -0.11991301  0.22255004  0.19674543 -0.31158444]
 [ 0.37727838  0.05894893 -0.34775138 -0.27623821 -0.06172332 -0.21989024
   0.02665496 -0.0942591   0.27506802  0.32177025]]
[[0 0 0 1 0 0 1 1 1 1]
 [0 1 0 1 0 0 1 0 1 1]]
[ 0.10341491 -0.11991301  0.22255004  0.19674543 -0.31158444  0.05894893
 -0.27623821  0.02665496  0.27506802  0.32177025]
[ 0.05894893  0.10341491 -0.27623821 -0.11991301  0.02665496  0.22255004
  0.19674543  0.27506802 -0.31158444  0.32177025]
FAILURE


ValueError: Shapes (2,) and (10,) are incompatible

In [19]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
mask = np.random.randint(0, 2, (2, 3, 2))
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.boolean_mask(np_x, mask))
fetch_mask = NDArrayDouble([2,3,2])
fetch_mask.FromNumpy(mask)
fetch_x.boolean_mask(fetch_mask)

print(mask)
print(np_z)
print(fetch_mask.ToNumpy())
print(fetch_x.ToNumpy())

test_fn(np_z, fetch_x)

[[[0 0]
  [0 0]
  [1 0]]

 [[0 0]
  [1 0]
  [0 1]]]
[ 0.18669058 -0.32598792  0.30494657]
[[[0. 0.]
  [0. 0.]
  [1. 0.]]

 [[0. 0.]
  [1. 0.]
  [0. 1.]]]
[[[ 0.01295559 -0.15427722]
  [ 0.39198399  0.34160343]
  [ 0.18669058  0.15737375]]

 [[-0.32004039  0.03149682]
  [-0.32598792  0.27380413]
  [-0.37525126  0.30494657]]]


ValueError: operands could not be broadcast together with shapes (3,) (2,3,2) 

### tf.dynamic_stitch

In [20]:
shape = [4]
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[4]) # ensure some values are negative
print("np_z before: ", np_z)
print("np_x: ", np_x)
print("np_y: ", np_y)
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.dynamic_stitch([[0, 2, 4, 5], [1, 3, 7, 6]], [np_x, np_y]))
print("np_z: ", np_z)

fetch_mask = NDArrayDouble(shape)
fetch_mask.FromNumpy(mask)
fetch_z.dynamic_stitch([[0, 2, 4, 5], [1, 3, 7, 6]], [fetch_x, fetch_y])

# print(mask)
# print(np_z)
# print(fetch_mask.ToNumpy())
print("fetch_z: ", fetch_z.ToNumpy())
print("fetch_x: ", fetch_x.ToNumpy())
print("fetch_y: ", fetch_y.ToNumpy())

# test_fn(np_z, fetch_z)

np_z before:  [ 0.18669058 -0.32598792  0.30494657]
np_x:  [ 0.25598943 -0.29110931  0.19630102 -0.33280305]
np_y:  [ 0.06156538 -0.3668807   0.16483509  0.28016623]
np_z:  [ 0.25598943  0.06156538 -0.29110931 -0.3668807   0.19630102 -0.33280305
  0.28016623  0.16483509]
fetch_z:  [ 0.25598943  0.06156538 -0.29110931 -0.3668807 ]
fetch_x:  [ 0.25598943 -0.29110931  0.19630102 -0.33280305]
fetch_y:  [ 0.06156538 -0.3668807   0.16483509  0.28016623]


### tf.scatter_update

In [21]:
# 1-dim example
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[10]) # ensure some values are negative
# updates = [[1, 0, 0, 0],[1, 0, 0, 0]]
# indices = [0, 1]
updates = [1, 5, 3]
indices = [7, 0, 2]

with tf.Session(graph=g) as sess:
    tf_x = tf.Variable(initial_value=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    tf_y = tf.scatter_update(tf_x, indices, updates)
    sess.run(tf.global_variables_initializer())

    np_x = sess.run(tf_x)
    tf_z = sess.run(tf_y)
fetch_x.FromNumpy(np_x)
fetch_x.scatter(updates, indices)
test_fn(tf_z, fetch_x)

test passed!


In [ ]:
# 2-dim example
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[4, 2]) # ensure some values are negative
updates = [[1, 0, 0, 0],[1, 0, 0, 0]]
indices = [0, 1]
# updates = [[0, 1, 2], [1, 2, 3], [3, 4, 5]]
# indices = [0, 1, 2]

with tf.Session(graph=g) as sess:
    tf_x = tf.Variable(initial_value=[[0, 0, 0, 0], [0, 0, 0, 0]])
    tf_y = tf.scatter_update(tf_x, indices, updates)
    sess.run(tf.global_variables_initializer())

    np_x = sess.run(tf_x)
    tf_z = sess.run(tf_y)
fetch_x.FromNumpy(np_x)
# fetch_x.scatter(updates, indices)
fetch_x.scatter([1, 0, 0, 0, 1, 0, 0, 0], [0, 4])

test_fn(tf_z, fetch_x)

### tf.gather

### tf.concat

### tf.transpose

### tf.expand_dims

### tf.where

### tf.assign

In [21]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    temp = tf.Variable(np_x)
    np_z = sess.run(temp.assign(np_y))
fetch_z = fetch_y
test_fn(np_z, fetch_z)

test passed!


### tf.shape

In [22]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.shape(np_x))
fetch_z = fetch_x.shape()

print(np_z)
print(fetch_z)
# test_fn(np_z, fetch_z)

[2 3 2]
[2, 3, 2]


### tf.reshape

In [59]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    temp = tf.Variable(np_x)
    np_z = sess.run(tf.reshape(np_x, [3, 4]))
fetch_z = fetch_x
fetch_z.reshape([3, 4])
print(np_z)
print(fetch_z.ToNumpy())
test_fn(np_z, fetch_z)

[[ 0.29458459  0.09859693  0.12309551 -0.31007651]
 [ 0.14908363 -0.1881486  -0.00182104  0.12289576]
 [-0.31379884 -0.37216433 -0.3720584   0.37793926]]
[[ 0.29458459 -0.31379884  0.09859693 -0.37216433]
 [-0.00182104  0.14908363  0.12289576 -0.1881486 ]
 [ 0.12309551 -0.3720584  -0.31007651  0.37793926]]
FAILURE


### tf.cond

### tf.map_fn

### tf.equal

In [64]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.equal(np_x, np_y))
fetch_z = (fetch_x == fetch_y)
test_fn(np_z, fetch_z)

AttributeError: 'bool' object has no attribute 'ToNumpy'

### tf.reduce_any

In [61]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.reduce_any(np_x, 1))
fetch_z.reduce_any(fetch_x, 1)
test_fn(np_z, fetch_z)

test passed!
