In [1]:
import numpy as np
import fetch.math as fm
from fetch.math import NDArrayDouble
import tensorflow as tf

In [2]:
TOLERANCE = 1e-12
def simple_test_fn(a, b):
    if (abs(a - b) < TOLERANCE):
        print("test passed!")
    else:
        print("FAILURE")
    return

In [3]:
def test_fn(np_arr, fetch_arr):
    
    if hasattr(fetch_arr, 'ToNumpy'):
        if np.allclose(np_arr, fetch_arr.ToNumpy()):
            print("test passed!")
        else:
            print("FAILURE")
        return
    else:
        if np.allclose(np_arr, fetch_arr):
            print("test passed!")
        else:
            print("FAILURE")
        return
        

### Setup

In [4]:
g = tf.Graph()

In [5]:
def reset_arrays(offset=0, shape=[2, 3, 2]):
    # initialise some random arrays
#     shape = [1,2,3,4,5,6]
#     shape = [2,4]
#     shape = [2,3,2]

    # set up the tensorflow / numpy array
    with g.as_default():
        tf_x = tf.to_double(tf.random_uniform(shape, 0.1, 1, dtype=tf.float64)) + offset
        tf_y = tf.to_double(tf.random_uniform(shape, 0.1, 1, dtype=tf.float64)) + offset
    with tf.Session(graph=g) as sess:
        sess.run(tf.global_variables_initializer())
        np_x = sess.run(tf_x)
        np_y = sess.run(tf_y)

    # set up the fetch array
    fetch_x = NDArrayDouble(shape)
    fetch_x.FromNumpy(np_x)
    fetch_y = NDArrayDouble(shape)
    fetch_y.FromNumpy(np_y)

    # set up a test fetch array
    fetch_z = NDArrayDouble(shape)
    
    return np_x, np_y, fetch_x, fetch_y, fetch_z

### tf.log

In [6]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.log(np_x))
fetch_x.log()
test_fn(np_z, fetch_x)

test passed!


### tf.exp

In [7]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.exp(np_x))
fetch_x.exp()
test_fn(np_z, fetch_x)

test passed!


### tf.sqrt

In [8]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.sqrt(np_x))
fetch_x.sqrt()
test_fn(np_z, fetch_x)

test passed!


### tf.div

In [9]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.div(np_x, np_y))
fetch_z = fetch_x / fetch_y
test_fn(np_z, fetch_z)

test passed!


### tf.multiply

In [10]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.multiply(np_x, np_y))
fetch_z = fetch_x * fetch_y
test_fn(np_z, fetch_z)

test passed!


### tf.nn.l2loss

In [11]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays()
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.nn.l2_loss(np_x))
fetch_z = fetch_x.l2loss()  
simple_test_fn(np_z, fetch_z)

test passed!


### tf.abs

In [12]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.abs(np_x))
fetch_x.abs()
test_fn(np_z, fetch_x)

test passed!


### tf.nn.relu

In [13]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.nn.relu(np_x))
fetch_x.relu()
test_fn(np_z, fetch_x)

test passed!


### tf.sign

In [14]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.sign(np_x))
fetch_x.sign()
test_fn(np_z, fetch_x)

test passed!


### tf.maximum

In [15]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.maximum(np_x, np_y))

fetch_z.maximum(fetch_x, fetch_y)

test_fn(np_z, fetch_z)

test passed!


### tf.reduce_mean

In [16]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.reduce_mean(np_x, 1))
fetch_z.reduce_mean(fetch_x, 1)
test_fn(np_z, fetch_z)

test passed!


### tf.reduce_sum

In [17]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.reduce_sum(np_x, 1))
fetch_z.reduce_sum(fetch_x, 1)
test_fn(np_z, fetch_z)

test passed!


### tf.boolean_mask

In [18]:
# 1d test
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[10]) # ensure some values are negative
mask = np.random.randint(0, 2, (10))
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.boolean_mask(np_x, mask))
fetch_mask = NDArrayDouble([10])
fetch_mask.FromNumpy(mask)
fetch_z = fetch_x.boolean_mask(fetch_mask)

test_fn(np_z, fetch_z)

test passed!


In [19]:
# 2d test
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[3, 4]) # ensure some values are negative
mask = np.random.randint(0, 2, (3, 4))
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.boolean_mask(np_x, mask))
fetch_mask = NDArrayDouble([3, 4])
fetch_mask.FromNumpy(mask)
fetch_z = fetch_x.boolean_mask(fetch_mask)

test_fn(np_z, fetch_z)

test passed!


In [20]:
#3d test
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[2,3,2]) # ensure some values are negative
mask = np.random.randint(0, 2, (2, 3, 2))
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.boolean_mask(np_x, mask))
fetch_mask = NDArrayDouble([2,3,2])
fetch_mask.FromNumpy(mask)
fetch_z = fetch_x.boolean_mask(fetch_mask)

test_fn(np_z, fetch_z)

test passed!


### tf.dynamic_stitch

In [21]:
# 1d example
output_shape = [8]
np_x, np_y, _, _, _ = reset_arrays(offset=-0.5, shape=[4]) # ensure some values are negative
indices = [[0, 2, 4, 5], [1, 3, 7, 6]]
updates = [np_x, np_y]
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.dynamic_stitch(indices, updates))

fetch_indices = NDArrayDouble([2, 4])
fetch_indices.FromNumpy(indices)
fetch_updates = NDArrayDouble()
fetch_updates.FromNumpy(updates)
fetch_z = NDArrayDouble(output_shape)
fetch_z = fetch_z.dynamic_stitch(fetch_indices, fetch_updates)

test_fn(np_z, fetch_z)

test passed!


In [22]:
# 2d example
output_shape = [16]
np_x, np_y, _, _, _ = reset_arrays(offset=-0.5, shape=[2, 4])
indices = [[[0, 2, 4, 5], [1, 3, 7, 6]], [[15, 14, 13, 12], [11, 10, 9, 8]]]
updates = [np_x, np_y]
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.dynamic_stitch(indices, updates))

fetch_indices = NDArrayDouble([2, 4])
fetch_indices.FromNumpy(indices)
fetch_updates = NDArrayDouble()
fetch_updates.FromNumpy(updates)
fetch_z = NDArrayDouble(output_shape)
fetch_z = fetch_z.dynamic_stitch(fetch_indices, fetch_updates)

test_fn(np_z, fetch_z)

test passed!


### tf.scatter_update

In [23]:
# 1-dim example
output_shape = [10]
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=output_shape) # ensure some values are negative
# updates = [[1, 0, 0, 0],[1, 0, 0, 0]]
# indices = [0, 1]
updates = [1, 5, 3]
indices = [7, 0, 2]

with tf.Session(graph=g) as sess:
    tf_x = tf.Variable(initial_value=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    tf_y = tf.scatter_update(tf_x, indices, updates)
    sess.run(tf.global_variables_initializer())

    np_x = sess.run(tf_x)
    np_z = sess.run(tf_y)

    
fetch_indices = NDArrayDouble()
fetch_indices.FromNumpy(indices)
fetch_updates = NDArrayDouble()
fetch_updates.FromNumpy(updates)
fetch_z = NDArrayDouble(output_shape)
fetch_z.scatter(fetch_updates, fetch_indices)
# this alternative syntax also works
# fetch_z = fetch_z.scatter(fetch_updates, [7, 0, 2])

test_fn(np_z, fetch_z)

test passed!


In [24]:
# 2-dim example
output_shape = [8]
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[2, 2]) # ensure some values are negative
updates = [[[0, 2], [1, 3]], [[4, 7], [6, 5]]]
indices = [[[0, 2], [1, 3]], [[4, 7], [6, 5]]]
with tf.Session(graph=g) as sess:
    tf_x = tf.Variable(initial_value=[0, 0, 0, 0, 0, 0, 0, 0])
    tf_y = tf.scatter_update(tf_x, indices, updates)
    sess.run(tf.global_variables_initializer())

    np_x = sess.run(tf_x)
    np_z = sess.run(tf_y)
    
fetch_indices = NDArrayDouble()
fetch_indices.FromNumpy([0, 2, 1, 3, 4, 7, 6, 5])
fetch_updates = NDArrayDouble()
fetch_updates.FromNumpy(updates)
fetch_z = NDArrayDouble(output_shape)
fetch_z.scatter(fetch_updates, fetch_indices)

test_fn(np_z, fetch_z)

test passed!


### tf.gather

In [25]:
# 1-dim example
output_shape = [10]
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[10]) # ensure some values are negative

indices = [0, 3, 4, 5, 8]
updates = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
with tf.Session(graph=g) as sess:
    tf_x = tf.Variable(initial_value=updates)
    tf_indices = tf.Variable(initial_value=indices)
    tf_y = tf.gather(tf_x, tf_indices)
    sess.run(tf.global_variables_initializer())

    np_x = sess.run(tf_x)
    np_z = sess.run(tf_y)

fetch_indices = NDArrayDouble()
fetch_indices.FromNumpy(indices)
fetch_updates = NDArrayDouble()
fetch_updates.FromNumpy(updates)
fetch_z = NDArrayDouble(output_shape)
fetch_z.gather(fetch_updates, fetch_indices)
# this alternative syntax also works
# fetch_z = fetch_z.gather(fetch_updates, fetch_indices)

test_fn(np_z, fetch_z)

test passed!


### tf.concat

In [29]:
# 1-dim example
output_shape = [10]
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[10]) # ensure some values are negative

with tf.Session(graph=g) as sess:
    tf_z = tf.concat([np_x, np_y], 0)
    sess.run(tf.global_variables_initializer())

    np_z = sess.run(tf_z)

fetch_z = NDArrayDouble(20)
fetch_z.concat([fetch_x, fetch_y], 0)

test_fn(np_z, fetch_z)

test passed!


In [32]:
# 1-dim example
output_shape = [10]
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5, shape=[2, 5]) # ensure some values are negative

with tf.Session(graph=g) as sess:
    tf_z = tf.concat([np_x, np_y], 0)
    sess.run(tf.global_variables_initializer())

    np_z = sess.run(tf_z)

fetch_z = NDArrayDouble(20)
fetch_z.concat([fetch_x, fetch_y], 0)

test_fn(np_z, fetch_z)

[[-0.27221715  0.21786031 -0.37554127 -0.29398566 -0.15427103]
 [-0.26967671  0.29466879 -0.32842657 -0.36560897 -0.27353985]
 [ 0.36532943  0.2780249   0.33749731  0.10480096 -0.35394547]
 [ 0.17612914  0.32161769  0.01698447  0.3478916   0.33026035]]
(4, 5)
[4, 5]
test passed!


### tf.transpose

### tf.expand_dims

### tf.where

### tf.assign

In [28]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    temp = tf.Variable(np_x)
    np_z = sess.run(temp.assign(np_y))
fetch_z = fetch_y
test_fn(np_z, fetch_z)

test passed!


### tf.shape

In [65]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.shape(np_x))
fetch_z = fetch_x.shape()

test_fn(np_z, np.array(fetch_z))

test passed!


### tf.reshape

In [66]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    temp = tf.Variable(np_x)
    np_z = sess.run(tf.reshape(np_x, [3, 4]))
fetch_z = fetch_x
fetch_z.reshape([3, 4])
print(np_z)
print(fetch_z.ToNumpy())
test_fn(np_z, fetch_z)

[[-0.05170785  0.04926507 -0.24981198  0.38580164]
 [ 0.12927471  0.3782015   0.26630379  0.19370452]
 [ 0.26199668  0.29321405 -0.38707852  0.2956453 ]]
[[-0.05170785  0.26199668  0.04926507  0.29321405]
 [ 0.26630379  0.12927471  0.19370452  0.3782015 ]
 [-0.24981198 -0.38707852  0.38580164  0.2956453 ]]
FAILURE


### tf.cond

### tf.map_fn

### tf.equal

In [ ]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.equal(np_x, np_y))
fetch_z = (fetch_x == fetch_y)
test_fn(np_z, fetch_z)

### tf.reduce_any

In [61]:
np_x, np_y, fetch_x, fetch_y, fetch_z = reset_arrays(offset=-0.5) # ensure some values are negative
with tf.Session(graph=g) as sess:
    np_z = sess.run(tf.reduce_any(np_x, 1))
fetch_z.reduce_any(fetch_x, 1)
test_fn(np_z, fetch_z)

test passed!
