### Initially we set up some arrays

In [77]:
# import fetch
import numpy as np

In [78]:
import fetch.math as fm
from fetch.math import NDArrayDouble
from fetch.math import statistics as stats

In [79]:
shape = [1,2,3,4,5]
n_dims = len(shape)

In [80]:
x = NDArrayDouble(shape)
y = NDArrayDouble(shape)
z = NDArrayDouble(shape)

In [81]:
for i in range(x.size()):
    x[i] = i + 1
    y[i] = -i -1
    z[i] = 5

In [82]:
x.ToNumpy()[:10]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [83]:
y.ToNumpy()[:10]

array([ -1.,  -2.,  -3.,  -4.,  -5.,  -6.,  -7.,  -8.,  -9., -10.])

just some housekeeping...

In [84]:
def test_pass_fn(test_list, z_list):
    test_pass = 1
    for idx in range(len(test_list)):
        if (z_list[idx] != test_list[idx]):
            test_pass = 0
    if test_pass:
        print("test passed!")
    else:
        print("FAILURE!!!!")

### Check copy and equality

In [85]:
y = x
test_pass_fn(y, x)

test passed!


In [86]:
y.ToNumpy()[:10]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [87]:
x.ToNumpy()[:10]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [88]:
if(y == x):
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


In [89]:
if not (y != x):
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


### Check basic element-wise arithmetic operators

In [90]:
test_list = [a + b for a,b in zip(x.ToNumpy(), y.ToNumpy())]
z = x + y
test_pass_fn(test_list, z)

test passed!


In [91]:
test_list = [a - b for a,b in zip(x.ToNumpy(), y.ToNumpy())]
z = x - y
test_pass_fn(test_list, z)

test passed!


In [92]:
test_list = [a * b for a,b in zip(x.ToNumpy(), y.ToNumpy())]
z = x * y
test_pass_fn(test_list, z)

test passed!


In [93]:
test_list = [a / b for a,b in zip(x.ToNumpy(), y.ToNumpy())]
z = x / y
test_pass_fn(test_list, z)

test passed!


### check basic array * scalar arithmetic operations

In [94]:
test_list = [a + 7 for a in x.ToNumpy()]
z = x + 7
test_pass_fn(test_list, z)

test passed!


In [95]:
test_list = [a - 7 for a in x.ToNumpy()]
z = x - 7
test_pass_fn(test_list, z)

test passed!


In [96]:
test_list = [a * 7 for a in x.ToNumpy()]
z = x * 7
test_pass_fn(test_list, z)

test passed!


In [97]:
test_list = [a / 7 for a in x.ToNumpy()]
z = x / 7
test_pass_fn(test_list, z)

test passed!


### check array slicing and slice assignment

In [108]:
y = x[0:1, 0:1, 0:2, 0:3, 0:2]

In [109]:
y.Shape()

[1, 1, 2, 3, 2]

In [110]:
y[0:1, 0:1, 0:2, 0:3, 0:2] = x[0:1, 0:1, 0:2, 0:3, 0:2]

In [111]:
some_value = x[0, 0, 1, 2, 1]

In [112]:
y[0,0,1,2,1] = x[0,0,1,2,1]

### check some other basic array methods

In [113]:
y.Reshape([2,6])
y.Shape()

[2, 6]

In [114]:
y.Reshape([999999,12])
y.Shape()

IndexError: 

In [115]:
y.Flatten().Shape()

[12]

### numpy style max and min

In [116]:
z = NDArrayDouble([2, 3])
for i in range(z.size()):
    z[i] = i + 1

In [117]:
z.ToNumpy()

array([1., 2., 3., 4., 5., 6.])

In [118]:
test_arr = np.array([[1,2,3],[4,5,6]])

In [119]:
test_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
cur_ax = 0
test_list = list(test_arr.max(axis=cur_ax))
cur_z = z.Max(cur_ax).ToNumpy()
test_pass_fn(test_list, cur_z)

FAILURE!!!!


In [125]:
test_list

[4, 5, 6]

In [126]:
cur_z

array([5., 6., 0.])

In [127]:
cur_ax = 0
test_list = list(test_arr.min(axis=cur_ax))
cur_z = z.Min(cur_ax).ToNumpy()
test_pass_fn(test_list, cur_z)

FAILURE!!!!


In [128]:
z.Max(1).ToNumpy()

array([2., 4.])

### check some more advanced math functions

In [129]:
x.ToNumpy()[:10]

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [130]:
test_list = [np.log(a) for a in x.ToNumpy()]
z.Log(x)
test_pass_fn(test_list, z)

test passed!


In [131]:
test_list = [np.exp(a) for a in x.ToNumpy()]
z.Exp(x)
test_pass_fn(test_list, z)

test passed!


In [132]:
test_list = [np.sqrt(a) for a in x.ToNumpy()]
z.Sqrt(x)
test_pass_fn(test_list, z)

test passed!


In [133]:
test_list = [np.power(a, 2) for a in x.ToNumpy()]
z.Pow(x)
test_pass_fn(test_list, z)

AttributeError: 'fetch.math.NDArrayDouble' object has no attribute 'Pow'

In [134]:
test_list = [np.sin(a) for a in x.ToNumpy()]
z.Sin(x)
test_pass_fn(test_list, z)

test passed!


In [135]:
test_list = [np.cos(a) for a in x.ToNumpy()]
z.Cos(x)
test_pass_fn(test_list, z)

test passed!


In [136]:
test_list = [np.tan(a) for a in x.ToNumpy()]
z.Tan(x)
test_pass_fn(test_list, z)

test passed!


In [137]:
test_list = [np.abs(a) for a in x.ToNumpy()]
z.Abs(x)
test_pass_fn(test_list, z)

test passed!


### Now let's get a bit more fancy

In [138]:
def Relu(x):
    if x >= 0:
        return x
    else:
        return 0
test_list = [Relu(a) for a in x.ToNumpy()]
z.Relu(x * 1)
test_pass_fn(test_list, z)

test passed!


In [139]:
z.ToNumpy()

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120.])

In [140]:
z.Relu(x * -1)
test_pass_fn(test_list, z)

test passed!


In [141]:
test_list = np.sign(x.ToNumpy())
z.Sign(x)
test_pass_fn(test_list, z)

FAILURE!!!!


In [142]:
test_list

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [143]:
z.Sign(1).ToNumpy()

TypeError: Sign(): incompatible function arguments. The following argument types are supported:
    1. (self: fetch.math.NDArrayDouble, arg0: fetch.math.NDArrayDouble) -> None

Invoked with: <fetch.math.NDArrayDouble object at 0x7fd89ac15068>, 1

In [144]:
z.Softmax()

AttributeError: 'fetch.math.NDArrayDouble' object has no attribute 'Softmax'