In [1]:
import fetch
import numpy as np

In [2]:
from fetch.math import NDArrayDouble

In [3]:
shape = [1,2,3,4,5]
n_dims = len(shape)

In [4]:
x = NDArrayDouble(shape)
y = NDArrayDouble(shape)


In [5]:
for i in range(x.size()):
    x[i] = i
    y[i] = 0

TypeError: __setitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: fetch.math.NDArrayDouble, arg0: List[slice], arg1: fetch.math.NDArrayDouble) -> fetch.math.NDArrayDouble
    2. (self: fetch.math.NDArrayDouble, arg0: List[List[int]], arg1: fetch.math.NDArrayDouble) -> fetch.math.NDArrayDouble

Invoked with: <fetch.math.NDArrayDouble object at 0x7f0e86354e30>, 0, 0

In [6]:
x.ToNumpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [7]:
y.ToNumpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [8]:
y = x

In [9]:
y.ToNumpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [10]:
x.ToNumpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])

In [11]:
view = [[0, 1, 1], [0, 1, 1], [0, 2, 1], [0, 3, 1], [0, 2, 1]]
y = x.__getitem__(view)

In [12]:
y.ToNumpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
y.Shape()

[1, 1, 2, 3, 2]

In [14]:
y.Flatten().Shape()

[12]

Checking numpy style slicing

In [24]:
y = x[0:1, 0:1, 0:2, 0:3, 0:2]

In [25]:
y.ToNumpy()

array([ 0.,  2.,  6.,  8., 12., 14., 24., 26., 30., 32., 36., 38.])

In [29]:
z = np.zeros([3, 4, 3])

In [30]:
z[0:2, 0:3, 0:2]

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

Checking numpy style slice assignment


In [32]:
x[0:1, 0:1, 0:1, 0:1, 0:2] = [0., 2.]

TypeError: __setitem__(): incompatible function arguments. The following argument types are supported:
    1. (self: fetch.memory.ShapeLessArrayDouble, arg0: int, arg1: float) -> None

Invoked with: <fetch.math.NDArrayDouble object at 0x7fcaf8610960>, (slice(0, 1, None), slice(0, 1, None), slice(0, 1, None), slice(0, 1, None), slice(0, 2, None)), [0.0, 2.0]

(2, 3, 2)

array([0.])