## A series of tests for the fetch math library (and associated python bindings)

### initial setup

In [1]:
# import fetch
import numpy as np
import fetch.math as fm
from fetch.math import NDArrayDouble
#from fetch.math import statistics as stats

In [2]:
def simple_test_fn(a, b):
    if (a == b):
        print("test passed!")
    else:
        print("FAILURE")
    return

In [3]:
def test_fn(np_arr, fetch_arr):
    
    if np.array_equal(np_arr, fetch_arr.ToNumpy()):
        print("test passed!")
    else:
        print("FAILURE")

    return

### Check To and From Numpy

In [4]:
shape = [1,2,3,4,5]
n_dims = len(shape)

In [5]:
# To Numpy Test
np_z = np.random.random(shape)
fetch_z = NDArrayDouble(shape)
fetch_z.FromNumpy(np_z)
#test_fn(np_z, fetch_z)

In [6]:
# From Numpy Test
np_z = np.random.random(shape)
fetch_z = NDArrayDouble(shape)
fetch_z.FromNumpy(np_z)
test_fn(np_z, fetch_z)

test passed!


### Check zeroes, ones, copy, and equality

In [7]:
shape = [1,2,3,4,5]
n_dims = len(shape)

In [8]:
np_x = np.zeros(shape)
fetch_x = NDArrayDouble.Zeros(shape)
np_y = np.ones(shape)
fetch_y = NDArrayDouble.Ones(shape)

fetch_z = NDArrayDouble(shape)

In [9]:
fetch_z = fetch_x
simple_test_fn(fetch_z, fetch_x)

test passed!


In [10]:
test_fn(np_x, fetch_z)

test passed!


In [11]:
fetch_z = fetch_y
simple_test_fn(fetch_z, fetch_y)

test passed!


In [12]:
if not (fetch_z != fetch_y):
    print("test passed!")
else:
    print("FAILURE!!!!")

test passed!


### Check basic element-wise arithmetic operators

In [13]:
shape = [3, 4]
n_dims = len(shape)
np_x = np.random.random(shape)
fetch_x = NDArrayDouble.Zeros(shape)
fetch_x.FromNumpy(np_x)
np_y = np.ones(shape)
fetch_y = NDArrayDouble.Ones(shape)
fetch_y.FromNumpy(np_y)

In [14]:
np_test = np_x + np_y
fetch_z = fetch_x + fetch_y
test_fn(np_test, fetch_z)

test passed!


In [15]:
np_test += np_x
fetch_z += fetch_x
test_fn(np_test, fetch_z)

test passed!


In [16]:
np_test = np_x - np_y
fetch_z = fetch_x - fetch_y
test_fn(np_test, fetch_z)

test passed!


In [17]:
np_test -= np_x
fetch_z -= fetch_x
test_fn(np_test, fetch_z)

test passed!


In [18]:
np_test = np_x * np_y
fetch_z = fetch_x * fetch_y
test_fn(np_test, fetch_z)

test passed!


In [19]:
np_test *= np_x
fetch_z *= fetch_x
test_fn(np_test, fetch_z)

test passed!


In [20]:
np_test = np_x / np_y
fetch_z = fetch_x / fetch_y
test_fn(np_test, fetch_z)

test passed!


In [21]:
np_test /= np_x
fetch_z /= fetch_x
test_fn(np_test, fetch_z)

test passed!


### check basic array * scalar arithmetic operations

In [22]:
shape = [3, 4]
n_dims = len(shape)
np_x = np.random.random(shape)
fetch_x = NDArrayDouble.Zeros(shape)
fetch_x.FromNumpy(np_x)
fetch_z = NDArrayDouble.Zeros(shape)
fetch_z.FromNumpy(np_x)

In [23]:
np_test = np_x + 7
fetch_z = fetch_x + 7
test_fn(np_test, fetch_z)

test passed!


In [24]:
np_test += 7
fetch_z += 7
test_fn(np_test, fetch_z)

test passed!


In [25]:
np_test = np_x - 7
fetch_z = fetch_x - 7
test_fn(np_test, fetch_z)

test passed!


In [26]:
np_test -= 7
fetch_z -= 7
test_fn(np_test, fetch_z)

test passed!


In [27]:
np_test = np_x * 7
fetch_z = fetch_x * 7
test_fn(np_test, fetch_z)

test passed!


In [28]:
np_test *= 7
fetch_z *= 7
test_fn(np_test, fetch_z)

test passed!


In [29]:
np_test = np_x / 7
fetch_z = fetch_x / 7
test_fn(np_test, fetch_z)

test passed!


In [30]:
np_test /= 7
fetch_z /= 7
test_fn(np_test, fetch_z)

test passed!


### check broadcasting arithmetic

In [31]:
shape = [3, 1, 5]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)

shape2 = [1, 7, 5]
np_y = np.random.random(shape2)
fetch_y = NDArrayDouble.Ones(shape2)
fetch_y.FromNumpy(np_y)

broadcast_shape = [max(a,b) for a,b in zip(shape, shape2)]

In [33]:
np_out = np_x + np_y
fetch_out = fetch_x + fetch_y
test_fn(np_out, fetch_out)

test passed!


In [34]:
np_out = np_x - np_y
fetch_out = fetch_x - fetch_y
test_fn(np_out, fetch_out)

test passed!


In [35]:
np_out = np_x * np_y
fetch_out = fetch_x * fetch_y
test_fn(np_out, fetch_out)

test passed!


In [36]:
np_out = np_x / np_y
fetch_out = fetch_x / fetch_y
test_fn(np_out, fetch_out)

test passed!


In [37]:
# The following shows examples of inline arithmetic with broadcasting - in numpy they do not support this
shape = [3, 1, 5]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

shape2 = [1, 7, 5]
np_y = np.ones(shape2)
fetch_y = NDArrayDouble.Ones(shape2)

broadcast_shape = [max(a,b) for a,b in zip(shape, shape2)]

In [38]:
try:
    fetch_x += fetch_y
except ValueError:
    print("test passed!")

broadcast shape ( [3, 7, 5] ) does not match shape of output array ( [3, 1, 5] )
test passed!


In [39]:
try:
    fetch_x -= fetch_y
except ValueError:
    print("test passed!")

broadcast shape ( [3, 7, 5] ) does not match shape of output array ( [3, 1, 5] )
test passed!


In [40]:
try:
    fetch_x *= fetch_y
except ValueError:
    print("test passed!")

broadcast shape ( [3, 7, 5] ) does not match shape of output array ( [3, 1, 5] )
test passed!


In [41]:
try:
    fetch_x /= fetch_y
except ValueError:
    print("test passed!")

broadcast shape ( [3, 7, 5] ) does not match shape of output array ( [3, 1, 5] )
test passed!


### check array slicing and slice assignment

In [42]:
shape = [3, 4, 5, 8, 2]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

In [43]:
np_y = np_x[0:1, 0:2, 2:3, 3:6, 0:1]
fetch_y = fetch_x[0:1, 0:2, 2:3, 3:6, 0:1]
test_fn(np_y, fetch_y)

test passed!


In [44]:
shape = [3, 4, 5, 8, 2]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)
shape = [1, 2, 3, 4, 1]
np_y = np.random.random(shape)
fetch_y = NDArrayDouble(shape)
fetch_y.FromNumpy(np_y)

np_y[0:1, 0:2, 0:3, 0:4, 0:1] = np_x[0:1, 2:4, 2:5, 2:6, 0:1]
fetch_y[0:1, 0:2, 0:3, 0:4, 0:1] = fetch_x[0:1, 2:4, 2:5, 2:6, 0:1]
test_fn(np_y, fetch_y)

test passed!


In [45]:
shape = [3, 4, 5, 8, 2]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)

In [46]:
np_y = np_x[1, 2, 3, 6, 1]
fetch_y = fetch_x[1, 2, 3, 6, 1]
simple_test_fn(np_y, fetch_y)

test passed!


In [47]:
shape = [3, 4, 5, 8, 2]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)
shape = [1, 2, 3, 4, 1]
np_y = np.random.random(shape)
fetch_y = NDArrayDouble(shape)
fetch_y.FromNumpy(np_y)

np_y[0, 1, 2, 3, 0] = np_x[2, 3, 4, 5, 1]
fetch_y[0, 1, 2, 3, 0] = fetch_x[2, 3, 4, 5, 1]
test_fn(np_y, fetch_y)

test passed!


### Reshaping tests

In [54]:
#shape = [3, 4, 5, 8, 2]
shape = [1,2,4]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)

new_shape = [1,2,1,2,2]
# new_shape = [4, 2, 8, 5, 3]
# new_shape = [2, 4, 1]


In [56]:
np_x = np.reshape(np_x, new_shape)
fetch_x.reshape(new_shape)
test_fn(np_x, fetch_x)
print(np_x)
print("\n")
print(fetch_x.ToNumpy())


FAILURE
[[[[[0.42301819 0.20348576]
    [0.40727856 0.04390191]]]


  [[[0.57985877 0.61751568]
    [0.4874134  0.48549057]]]]]


[[[[[0.42301819 0.40727856]
    [0.20348576 0.04390191]]]


  [[[0.57985877 0.4874134 ]
    [0.61751568 0.48549057]]]]]


In [57]:
absurd_shape = [99999, 12]
try:
    fetch_x.reshape(absurd_shape)
except ValueError:
    print("test passed!")

cannot reshape array of size ( 8 ) into shape of( [1, 2, 1, 2, 2] )
test passed!


In [58]:
shape = [3, 4, 5, 8, 2]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)

np_x = np_x.flatten()
fetch_x.flatten()
test_fn(np_x, fetch_x)

FAILURE


### check dimension reduction max and min functions with axis specification

In [59]:
# max_shape = [7, 4, 6]
# fetch_x = NDArrayDouble(max_shape)
# np_x = np.zeros(max_shape)
# counter = 0
# for i in range(max_shape[0]):
#     for j in range(max_shape[1]):
#         for k in range(max_shape[2]):
#             fetch_x[i, j, k] = counter
#             np_x[i, j, k] = counter
#             counter += 1

In [60]:
# # test taking max and min across all axes one by one
# out_shapes = [[4, 6], [7, 6], [7, 4]]
# for cur_ax in range(0, 3):

#     out_shape = out_shapes[cur_ax]
#     np_max = np_x.max(axis=cur_ax)
#     fetch_max = fetch_x.max(cur_ax)
#     np_min = np_x.min(axis=cur_ax)
#     fetch_min = fetch_x.min(cur_ax)

#     test_fn(np_max, fetch_max)
#     test_fn(np_min, fetch_min)

### check some more functions

In [61]:
shape = [3, 4]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)

In [62]:
np_x = np.abs(np_x)
fetch_x.abs(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [63]:
np_x = np.exp(np_x)
fetch_x.exp(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [64]:
np_x = np.exp2(np_x)
fetch_x.exp2(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [65]:
np_x = np.expm1(np_x)
fetch_x.expm1(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [66]:
np_x = np.log(np_x)
fetch_x.log(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [67]:
np_x = np.log10(np_x)
fetch_x.log10(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [68]:
np_x = np.log2(np_x)
fetch_x.log2(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [71]:
shape = [3, 4]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)

In [72]:
np_x = np.log1p(np_x)
fetch_x.log1p(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [73]:
shape = [3, 4]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)


In [74]:
np_x = np.sqrt(np_x)
fetch_x.sqrt(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [75]:
np_x = np.cbrt(np_x)
fetch_x.cbrt(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [76]:
np_x = np.sin(np_x)
fetch_x.sin(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [77]:
np_x = np.cos(np_x)
fetch_x.cos(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [78]:
np_x = np.tan(np_x)
fetch_x.tan(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [79]:
np_x = np.arcsin(np_x)
fetch_x.asin(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [80]:
np_x = np.arccos(np_x)
fetch_x.acos(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [81]:
np_x = np.arctan(np_x)
fetch_x.atan(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [82]:
np_x = np.sinh(np_x)
fetch_x.sinh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [83]:
np_x = np.cosh(np_x)
fetch_x.cosh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [84]:
np_x = np.tanh(np_x)
fetch_x.tanh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [85]:
shape = [3, 4]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

np_x = np.arcsinh(np_x)
fetch_x.asinh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [86]:
shape = [3, 4]
np_x = np.ones(shape)
fetch_x = NDArrayDouble.Ones(shape)

np_x = np.arccosh(np_x)
fetch_x.acosh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [87]:
np_x = np.arctanh(np_x)
fetch_x.atanh(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [88]:
np_x = np.ceil(np_x)
fetch_x.ceil(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [89]:
np_x = np.floor(np_x)
fetch_x.floor(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [90]:
np_x = np.trunc(np_x)
fetch_x.trunc(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [91]:
np_x = np.round(np_x)
fetch_x.round(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [92]:
np_x = np.rint(np_x)
fetch_x.rint(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [93]:
np_x = np.isfinite(np_x)
fetch_x.isfinite(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [94]:
np_x = np.isinf(np_x)
fetch_x.isinf(fetch_x)
test_fn(np_x, fetch_x)

test passed!


In [95]:
np_x = np.isnan(np_x)
fetch_x.isnan(fetch_x)
test_fn(np_x, fetch_x)

test passed!


### Now let's get a bit more fancy

In [108]:
def Relu(x):
    if x >= 0:
        return x
    else:
        return 0

In [109]:
shape = [3, 4]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)

fetch_x.relu(fetch_x)
for i in range(3):
    for j in range(4):
        np_x[i, j] = Relu(np_x[i, j])

test_fn(np_x, fetch_x)

test passed!


In [117]:
shape = [3, 4]
np_x = np.random.random(shape)
fetch_x = NDArrayDouble(shape)
fetch_x.FromNumpy(np_x)

np_x = np.sign(np_x)
fetch_x.sign(fetch_x)

test_fn(np_x, fetch_x)

test passed!


In [118]:
# shape = [3, 4]
# np_x = np.random.random(shape)
# fetch_x = NDArrayDouble(shape)
# fetch_x.FromNumpy(np_x)

# np_x = np.softmax(np_x)
# fetch_x.softmax(fetch_x)

# test_fn(np_x, fetch_x)

AttributeError: 'fetch.math.NDArrayDouble' object has no attribute 'softmax'