In [4]:
# This is a small client example that connects to examples/rpc/server.cpp
from libfetch.service.client import Client
MYPROTO = 1
SLOWFUNCTION = 1
c = Client()
c.Connect("localhost", 8080)
promise = c.Call(MYPROTO, SLOWFUNCTION, ('i32', 30), ('i32', 63))
promise.Wait()
print "The result is ", promise.AsInt32()
c.Disconnect()

The result is  93


In [1]:
import libfetchcore
import numpy as np
import mnist

In [8]:
def feed_forward(X, weights):
    a = [X]
    for w in weights:
        print "="*20
        print w
        a.append(sigmoid(a[-1].dot(w)))
    asfasfasf
    return a

In [9]:
def grads(X, Y, weights):
    grads = np.empty_like(weights)
    a = feed_forward(X, weights)
    delta = a[-1] - Y # cross-entropy
    grads[-1] = np.dot(a[-2].T, delta)
    for i in xrange(len(a)-2, 0, -1):
        delta = np.dot(delta, weights[i].T) * d_sigmoid(a[i])
        grads[i-1] = np.dot(a[i-1].T, delta)
    return grads / len(X)

In [10]:
sigmoid = lambda x: 1 / (1 + np.exp(-x))
d_sigmoid = lambda y: y * (1 - y)

trX, trY, teX, teY = mnist.load_data(one_hot=True)

weights = [
    np.random.randn(28*28, 100) / np.sqrt(28*28),
    np.random.randn(100, 10) / np.sqrt(100)]
num_epochs, batch_size, learn_rate = 30, 10, 0.2

## Micro program
for i in xrange(num_epochs): 

    ## Running empoc
    for j in xrange(0, len(trX), batch_size):
        X, Y = trX[j:j+batch_size], trY[j:j+batch_size]
        weights -= learn_rate * grads(X, Y, weights)

    ## Evaluating prediction
    prediction = np.argmax(feed_forward(teX, weights)[-1], axis=1)
    print i, np.mean(prediction == np.argmax(teY, axis=1))

[[-0.06068327  0.03333829 -0.06196534 ..., -0.0258947   0.04140007
   0.05997185]
 [ 0.04366584 -0.03451011 -0.02225932 ...,  0.00232072  0.01785942
  -0.02241192]
 [-0.00171679  0.07101834  0.06120929 ...,  0.00982338 -0.03878764
   0.01799382]
 ..., 
 [-0.00461613 -0.01580065 -0.04633312 ...,  0.01267862 -0.0058555
  -0.00547899]
 [ 0.02080119  0.0801724   0.02447236 ..., -0.00483342  0.05996223
   0.04557949]
 [ 0.02215157  0.07978969  0.00400964 ...,  0.00836241 -0.0163922
  -0.03085752]]
[[  9.92610961e-02   1.52172323e-01   2.97890023e-02  -7.06780429e-02
    1.55767365e-01   1.64005111e-03   1.33957295e-01  -5.71001116e-02
   -1.12056128e-01   1.25640045e-01]
 [  8.83089222e-02  -3.42012069e-03   1.68665981e-01   1.53629054e-01
   -4.07022060e-02  -1.88444152e-01  -2.68540624e-02   6.37424811e-02
    3.22102719e-02  -1.10771841e-01]
 [ -6.96338878e-02  -2.89534118e-02  -5.43796702e-02   2.70156448e-02
    1.36726687e-01  -2.79675201e-02  -5.86021346e-02  -4.43064466e-02
    1.00

NameError: global name 'asfasfasf' is not defined

In [2]:
dir(libfetchcore.fetch.math.linalg)

['MatrixDouble',
 'MatrixFloat',
 'MatrixInt16',
 'MatrixInt32',
 'MatrixInt64',
 'MatrixInt8',
 'MatrixUInt16',
 'MatrixUInt32',
 'MatrixUInt64',
 'MatrixUInt8',
 '__doc__',
 '__name__',
 '__package__']

In [3]:
m = libfetchcore.fetch.math.linalg.MatrixDouble()
m.Resize(4,4)
for i in range(m.height()):
    for j in range(m.width()):
        m[i, j] = 2 * i + j

In [4]:
print m.ToNumpy()

[[ 0.  1.  2.  3.]
 [ 2.  3.  4.  5.]
 [ 4.  5.  6.  7.]
 [ 6.  7.  8.  9.]]


In [5]:
m.FromNumpy( np.array([ [0,1,2,3,4],[0,1,2,3,4],[0,1,2,3,4],[0,1,2,3,4],[0,1,2,3,4] ] ))
print m.size(), m.height(), m.width()
print m[4,4]

25 5 5
4.0


In [6]:
m.ToNumpy()

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [7]:
q = libfetchcore.fetch.math.linalg.MatrixDouble(m.Copy())
q *= m

In [ ]:
q=m+m

In [9]:
for i in range(r.size()):
    r[i] = 3*i

In [10]:
print r.size()

16


In [11]:
for i in range(r.size()):
    print r[i]

0.0
3.0
6.0
9.0
12.0
15.0
18.0
21.0
24.0
27.0
30.0
33.0
36.0
39.0
42.0
45.0


In [14]:
r[1,1]

15.0

In [18]:
m.Resize(4,4)

In [19]:
m[3] = 12